site_name: LiLaC documentation
repo_url: https://github.com/opekope2/LiLaC
copyright: © 2022-2023 opekope2
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    scheme: slate
  features:
    - navigation.expand
    - content.code.copy
nav:
  - Home: index.md
  - API docs:
    - Latest: kdoc/latest
    #CI_KDOC_PLACEHOLDER
    - 1.0.0-beta.3: kdoc/1.0.0-beta.3
    - 1.0.0-beta.2: kdoc/1.0.0-beta.2
    - 1.0.0-beta.1: kdoc/1.0.0-beta.1
  - API docs (Java syntax):
    - Latest: javadoc/latest
    #CI_JAVADOC_PLACEHOLDER
    - 1.0.0-beta.3: javadoc/1.0.0-beta.3
    - 1.0.0-beta.2: javadoc/1.0.0-beta.2
    - 1.0.0-beta.1: javadoc/1.0.0-beta.1
markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.caret
extra_css:
  - stylesheets/chips.css
use_directory_urls: false
