name: Build project

on:
  workflow_call:
    inputs:
      build-project:
        type: boolean
      test-project:
        type: boolean
      build-docs:
        type: boolean
      upload-output:
        type: boolean
      fast:
        type: boolean

jobs:
  build:
    name: Build project
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Prepare build
        id: prepare
        run: |
          echo "upload=${{ inputs.upload-output && matrix.os == 'ubuntu-latest' }}" >> $GITHUB_OUTPUT
          echo "fast=${{ inputs.fast && matrix.os != 'ubuntu-latest' }}" >> $GITHUB_OUTPUT
      - name: Checkout repository
        if: steps.prepare.outputs.fast == 'false'
        uses: actions/checkout@v3
      - name: Validate gradle wrapper
        if: steps.prepare.outputs.fast == 'false'
        uses: gradle/wrapper-validation-action@v1
      - name: JDK setup
        if: steps.prepare.outputs.fast == 'false'
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
      - name: Build project
        if: inputs.build-project && steps.prepare.outputs.fast == 'false'
        run: ./gradlew build -x test
      - name: Test project
        if: inputs.test-project && steps.prepare.outputs.fast == 'false'
        run: ./gradlew test
      - name: Build documentation
        if: inputs.build-docs && steps.prepare.outputs.fast == 'false'
        run: ./gradlew dokkaHtml
      - name: Build documentation (Java syntax)
        if: inputs.build-docs && steps.prepare.outputs.fast == 'false'
        run: ./gradlew dokkaHtml -PjavaSyntax
      - name: Upload build output
        if: inputs.build-project && steps.prepare.outputs.upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: jars
          path: "*/build/libs/*.jar"
          if-no-files-found: error
      - name: Upload documentation output
        if: inputs.build-docs && steps.prepare.outputs.upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: kdoc
          path: "Api/build/docs/kotlinHtml"
          if-no-files-found: error
      - name: Upload documentation output (Java syntax)
        if: inputs.build-docs && steps.prepare.outputs.upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: javadoc
          path: "Api/build/docs/javaHtml"
          if-no-files-found: error
